### ISSUE TITLE
[Crash]: 1.20 server crash

### ISSUE THREAD

**Issue by drakosoldier298** [Fuzss/stoneworks#1]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20

### Mod Version (Required)

7.0.3

### Notes (Required)

Start server
server crash 

### Crash Report (Required)

https://mclo.gs/GX6Kxry

### latest.log (Optional)

https://mclo.gs/IrHX774

**Comment by Fuzss** [comment]
Thanks! Fixed in v7.0.1.
