### ISSUE TITLE
[Bug]: emi resources dont send to clients when using on client and server 

### ISSUE THREAD

**Issue by Taleuxss** [Fuzss/stoneworks#3]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

run server
join on client
open inv (without joining singleplayer world, if you go into a singleplayer world then the server the resources load BUT its only for block drops the recipes are still broken)
bottom left it says something like waiting for resources from server 

i also have the same issue with other mods named comforts and clutter

**Comment by Fuzss** [comment]
Stoneworks is extremely simple, all it does is add a couple of blocks and recipes. There isn't that much that can go wrong here. You should report this to EMI instead. Maybe it's an issue with the amount of recipes..
