### ISSUE TITLE
[Crash]: Crash due to the cycling of the icons on the tab in the creative menu

### ISSUE THREAD

**Issue by 2iqPlays** [Fuzss/stoneworks#5]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

Open Creative Inventory Screen
Scroll To Stoneworks Tab
Wait Until Stoneworks Tab Icon Scrolls To Basalt
Game Crashes After Basalt Icon

### Crash Report (Required)

https://gist.github.com/2iqPlays/950a652b18c180856ee359419559beb4

**Comment by Fuzss** [comment]
Fixed in v4.0.2.
